Feature/18121 Add cache for ServiceBusClient and Sender
CluedIn-io/CluedIn.Connector.AzureServiceBus pull request #13
Opened 2023-01-06 17:49 UTC by DmytroLohvynenko

Ref https://dev.azure.com/CluedIn-io/CluedIn/_workitems/edit/18121

Work is stacked up on https://dev.azure.com/CluedIn-io/CluedIn/_workitems/edit/18094, #12  which should be merged into release 3.4.0 and probably dev, before this PR.

So, reviewers - please check second(latest) commit.

2023-01-09 04:59 UTC, andrew-hardy requested changes

2023-01-09 04:59 UTC, andrew-hardy commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
> +            _serviceBusResourcesCache = new Dictionary<string, KeyValuePair<ServiceBusClient, ServiceBusSender>>();
Testing shows that CluedIn only instantiates the connector once and after several hours DisposeAsync was not called. Given this a static cache is dangerous as it will never expire. If a client or sender was to enter an error state than the connector will be poisoned until the pod is restarted. Consider injecting and using a cache instead.

2023-01-09 04:59 UTC, andrew-hardy commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
>          public override async Task StoreData(ExecutionContext executionContext, Guid providerDefinitionId, string containerName, IDictionary<string, object> data)
Now that clients and senders are cached should we recreate them before retrying if there was an error sending?

2023-01-09 04:59 UTC, andrew-hardy commented on .editorconfig
> +csharp_prefer_braces = when_multiline : suggestion
Was this intentional?

2023-01-09 04:59 UTC, andrew-hardy commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
> +        }
CluedIn doesn't currently call these

2023-01-12 16:54 UTC, DmytroLohvynenko commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
> +            _serviceBusResourcesCache = new Dictionary<string, KeyValuePair<ServiceBusClient, ServiceBusSender>>();
If we use cache - `IApplicationCache` here, with few hours of expiration, will it take care of calling `AsyncDispose`?

2023-01-12 16:58 UTC, DmytroLohvynenko commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
>          public override async Task StoreData(ExecutionContext executionContext, Guid providerDefinitionId, string containerName, IDictionary<string, object> data)
I would suggest wait and observe what errors we can get.

If any of them could be fixed with recreation of client/sender, than we can either flush the cache immediately and create brand new pair, or configure last retry to be out of expiration window - so it would pick new pair indirectly.

2023-01-12 18:46 UTC, DmytroLohvynenko commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
> +            _serviceBusResourcesCache = new Dictionary<string, KeyValuePair<ServiceBusClient, ServiceBusSender>>();
From what I found `IApplicationCache` won't call proper disposing, so I had to use `MemoryCache` here directly.

2023-01-12 18:49 UTC, DmytroLohvynenko commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
> +        }
Changed to `IDisposable`. Probably CluedIn doesn't call this also but I'm not sure if that matters a lot or no.

2023-01-13 04:33 UTC, andrew-hardy commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
>          public override async Task StoreData(ExecutionContext executionContext, Guid providerDefinitionId, string containerName, IDictionary<string, object> data)
Ok. Keep in mind we won't know what error are received in drive by ama installs unless we specifically went looking.

2023-01-13 04:34 UTC, andrew-hardy commented on .editorconfig
> +csharp_prefer_braces = when_multiline : suggestion
Not sure what the company coding standards are in this case, happy to leave as is

2023-01-13 04:42 UTC, andrew-hardy commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
> +            _serviceBusResourcesCache = new Dictionary<string, KeyValuePair<ServiceBusClient, ServiceBusSender>>();
The IApplicationCache is still being used in CreateContainer

2023-01-13 04:42 UTC, andrew-hardy requested changes

2023-01-13 04:42 UTC, andrew-hardy commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
>          private readonly IApplicationCache _cache;
The IApplicationCache is still being used in CreateContainer?

2023-01-13 04:43 UTC, andrew-hardy commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
> +        }
No it doesn't but it good practice :)

2023-01-13 04:45 UTC, andrew-hardy commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
> +            _serviceBusResourcesCache = new Dictionary<string, KeyValuePair<ServiceBusClient, ServiceBusSender>>();
I left my CluedIn running for a few hours, and it wasn't called. Even if it was, having a dead connection stuck for hours is a bit long. I would expect minutes, 10 max. Reconnecting every 10 minutes wouldn't have a noticeable effect on speed

2023-01-13 04:46 UTC, andrew-hardy commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
> +                AbsoluteExpiration = DateTimeOffset.UtcNow.AddHours(1),
Suggest 10 minutes. The performance effect of reconnecting every 10 minutes, vs every hour would be negligible. But if there was an issue the user would definitely feel the difference waiting 1 hour for it to self-heal

2023-01-13 12:39 UTC, DmytroLohvynenko commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
>          private readonly IApplicationCache _cache;
Yes, I haven't touched that place. 
It looks strange to me, but maybe there were some reasoning why it is implemented the way it is.

2023-01-13 12:44 UTC, DmytroLohvynenko commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
> +                AbsoluteExpiration = DateTimeOffset.UtcNow.AddHours(1),
++, changed to 10m

2023-01-15 20:42 UTC, andrew-hardy requested changes

2023-01-15 20:42 UTC, andrew-hardy commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
>          private readonly IApplicationCache _cache;
There is no special reason I used the IApplicationCache. Please update so that this class is dependent on only one cache.

2023-01-16 08:59 UTC, DmytroLohvynenko commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
>          private readonly IApplicationCache _cache;
++

2023-01-17 01:25 UTC, andrew-hardy reviewed
I just realized that the MemoryCache wasn't injected and started to think about this PR a bit more. Upon further consideration, there seems to be quite a lot of churn for the relatively small change of caching the sender. I have created a separate branch that achieves the same result without changing the caching library and modifying only `AzureServiceBusConnector.cs`. Please look at https://github.com/CluedIn-io/CluedIn.Connector.AzureServiceBus/tree/feature/18121_ASB_ClientCache2 when you can and let me know if it suites your needs.

2023-01-17 13:52 UTC, DmytroLohvynenko commented
> I just realized that the MemoryCache wasn't injected and started to think about this PR a bit more. Upon further consideration, there seems to be quite a lot of churn for the relatively small change of caching the sender. I have created a separate branch that achieves the same result without changing the caching library and modifying only `AzureServiceBusConnector.cs`. Please look at https://github.com/CluedIn-io/CluedIn.Connector.AzureServiceBus/tree/feature/18121_ASB_ClientCache2 when you can and let me know if it suites your needs.

Thank you, I have checked this branch. As we were discussing earlier - `IApplicationCache` doesn't provide any way for disposing resources when they expire. Potentially they will be cleared some time afterwards through garbage collection, but we have no control over how often GC will run.

Also, if in some future update CluedIn will stop caching `IConnector` forever, and will be disposing or throwing it away, current using shared cache will allow `AzureClient` and `AzureSender` to be kept for prolonged periods of time.

All of this looks like a risks for me, but if Azure-Integration team is good to go with it, that I'm fine.
Just need at least one of this PRs to be merged, so I can continue with refactoring plans, removing unused code, etc.

2023-01-19 05:26 UTC, andrew-hardy commented
Makes sense. I have updated the other branch to dispose on eviction, as well as use Microsoft.Extensions.Caching so we can inject the cache. Please take a look when you can

2023-01-19 14:06 UTC, DmytroLohvynenko commented
Replaced by https://github.com/CluedIn-io/CluedIn.Connector.AzureServiceBus/pull/16

2023-01-19 14:06 UTC, closed without merging