Feature/18119 remove unnecessary code
CluedIn-io/CluedIn.Connector.AzureServiceBus pull request #14
Opened 2023-01-06 19:10 UTC by DmytroLohvynenko

Ref:
https://dev.azure.com/CluedIn-io/CluedIn/_workitems/edit/18119
https://dev.azure.com/CluedIn-io/CluedIn/_workitems/edit/18120
https://dev.azure.com/CluedIn-io/CluedIn/_workitems/edit/18157

PR Based on changes from #13, they have higher priority and expected to be merged before current changes.

2023-01-20 06:58 UTC, devbryan0225 commented
PR naming convention:
https://www.conventionalcommits.org/en/v1.0.0/

Add `(AB#18016)` to the title in this PR. ex. `feat: Cleanup code (AB#18016)`

It will then tie your PR to your [PBI 18016](https://dev.azure.com/CluedIn-io/CluedIn/_workitems/edit/18016)

![image](https://user-images.githubusercontent.com/52289084/213635807-5e07a37d-e7aa-4517-a998-5602805983b1.png)

More on PRs:
https://dev.azure.com/CluedIn-io/CluedIn/_wiki/wikis/CluedIn.wiki/77/Pull-Request-Process

2023-01-20 07:35 UTC, devbryan0225 reviewed
please add summary of what is done here to the PR description for easier tracking

2023-01-20 07:35 UTC, devbryan0225 commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
> -
better to leave them where they are for ease of audit trail purposes, if they're only moved around.

2023-01-20 07:35 UTC, devbryan0225 commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
> -
better to leave them where they are for ease of audit trail purposes, if they're only moved around.

2023-01-20 14:12 UTC, DmytroLohvynenko commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
> -
My idea was to move them bellow all real code and hide in `#region NotImplementedMembers `, so developers would spend less time scrolling through them up and down when working with this class.

2023-01-20 14:16 UTC, DmytroLohvynenko commented on src/Connector.SqlServer/Connector/AzureServiceBusConnector.cs
> -
+

2023-01-23 21:51 UTC, andrew-hardy requested changes
In addition, please add a test rather than delete the test scaffolding

2023-01-23 21:51 UTC, andrew-hardy commented on Nuget.config
> +        <add key="release" value="https://pkgs.dev.azure.com/CluedIn-io/_packaging/release/nuget/v3/index.json" />
Revert the changes to this file as CluedIn.Connector.AzureServiceBus is a public repo and the release nuget feed is not public

2023-01-23 21:51 UTC, andrew-hardy commented on Packages.props
> +    <PackageReference Update="CluedIn.Connector.Common" Version="3.4.3" />
3.4.3 is not available on the public feed

2023-01-24 10:49 UTC, DmytroLohvynenko commented
> In addition, please add a test rather than delete the test scaffolding

I'm starting on project soon, not sure how much free time I will get, so at least I would like to finish with cleaning this repo.

2023-01-24 11:54 UTC, DmytroLohvynenko commented on Packages.props
> +    <PackageReference Update="CluedIn.Connector.Common" Version="3.4.3" />
how to add it there?

2023-01-25 06:34 UTC, andrew-hardy commented on Packages.props
> +    <PackageReference Update="CluedIn.Connector.Common" Version="3.4.3" />
release needs to be merged into master. I don't know if the release branch is ready for that though.

2023-01-27 00:49 UTC, DmytroLohvynenko commented on Nuget.config
> +        <add key="release" value="https://pkgs.dev.azure.com/CluedIn-io/_packaging/release/nuget/v3/index.json" />
++

2023-01-27 00:53 UTC, DmytroLohvynenko commented on Packages.props
> +    <PackageReference Update="CluedIn.Connector.Common" Version="3.4.3" />
Good suggestion, changed to 3.4.0.

For some weird reasons I wasn't able to check that `Connector.Common` available in Public.
If I click `release` for example, I could see package and versions.
But if I click `Public` - just white window.
![image](https://user-images.githubusercontent.com/25682289/214982852-4d762548-26bf-4522-a2b5-5500384733f4.png)
![image](https://user-images.githubusercontent.com/25682289/214982938-e80f226d-149f-4242-8814-57fdfed7092c.png)
![image](https://user-images.githubusercontent.com/25682289/214983029-0c440ed9-c830-40d2-b60b-a737efe3802f.png)

2023-01-30 10:35 UTC, andrew-hardy commented
Test scaffolding is still deleted. Please refer to my previous comment about adding a test rather than delete the test scaffolding.

2023-01-30 12:22 UTC, DmytroLohvynenko commented
> Test scaffolding is still deleted. Please refer to my previous comment about adding a test rather than delete the test scaffolding.


@andrew-hardy sorry but the work in question was about cleaning code in repository. Adding new features or tests were not in scope of related tasks.

Do I need to restore scaffolding (actually copy-pasted SQL Connector tests with disabled code, that always return false positives) to move on?

2023-03-15 04:35 UTC, andrew-hardy commented
I don't agree with referencing `CluedIn.Connector.Common`. `CluedIn.Connector.Common` contains breaking changes in every revision from 3.3 -> 3.4 -> 3.5 . It has been referenced in other connectors such as `CluedIn.Connector.AzureDataLake` and `Cluedin.Connector.AzureDedicatedSqlPool`, with the end result being that these connectors cannot run side by side with `CluedIn.Connector.SqlServer 3.3` (the current default in the AMA). 

I suggest closing this PR. Perhaps in the future if a backwards compatible `CluedIn.Connector.Common` is produced and backwards compatibility checks are performed on build it could be considered a safe dependency.

2023-04-05 09:57 UTC, andrew-hardy approved these changes

2023-04-05 09:58 UTC, merged